name: lolrag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - chainlit
    - httpx
    - pydantic
    - python-dotenv
    - uvloop; sys_platform != "win32"
    - winloop; sys_platform == "win32"
    - beautifulsoup4
    - psycopg2-binary
    - "psycopg[binary]"
    - psycopg-pool
    - aiohttp